### ISSUE TITLE
Primrose does not run on my system

### ISSUE THREAD

**Issue by micahbales** [NotionTheory/Primrose#149]
I tried to run the repo on my local system, and I got some errors. Does Primrose require a certain version of Node.js? Anything else I should know? 

Here's the errors I got:

`➜  Primrose git:(master) npm start

> primrose@0.31.2 start /Users/micahbales/Dropbox/Documents/Git/Primrose
> node node_modules/notion-node/default --url=Primrose/doc/editorVR

Serving from directory ..
Listening on port 80
starting:  open http://localhost/Primrose/doc/editorVR
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at Server._listen2 (net.js:1239:19)
    at listen (net.js:1288:10)
    at Server.listen (net.js:1384:5)
    at Object.<anonymous> (/Users/micahbales/Dropbox/Documents/Git/Primrose/node_modules/notion-node/default.js:19:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/micahbales/.nvm/versions/node/v6.3.1/bin/node" "/Users/micahbales/.nvm/versions/node/v6.3.1/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! primrose@0.31.2 start: `node node_modules/notion-node/default --url=Primrose/doc/editorVR`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the primrose@0.31.2 start script 'node node_modules/notion-node/default --url=Primrose/doc/editorVR'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the primrose package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/notion-node/default --url=Primrose/doc/editorVR
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs primrose
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls primrose
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/micahbales/Dropbox/Documents/Git/Primrose/npm-debug.log`

**Comment by kbouw** [comment]
Hey @micahbales 

Do you happen to have the latest version of the master repo? The error you're getting `Error: listen EACCES 0.0.0.0:80` is because anytime you spin up a server on a port below 3000, root permissions are required.

Running the command `sudo npm start` will resolve the error, but I changed the default port to 8080 in a recent commit to resolve this issue when running the project.

If you haven't already, `git pull` to grab the latest version of master and try rerunning the command `npm start`

**Comment by micahbales** [comment]
Thanks, Kristian. I do have the latest version pulled down from the repo. 

I didn't know that information about lower ports requiring admin privileges. So I'll need to use `sudo` whenever I want to run the project?

**Comment by kbouw** [comment]
Actually, the port declaration is [here] (https://github.com/NotionTheory/Primrose/blob/master/gulpfile.js#L140) but I see that it is apparently only being recognized for the gulp task `test`.

What happens if you run `npm test`? And yes, if you run `sudo npm start` it will run properly. I will fix this as soon as I get home.

**Comment by capnmidnight** [comment]
Yes, looks like I forgot to update the `npm start` task. You should just be able to run `gulp` to both start the build tasks and run the dev server.

**Comment by kbouw** [comment]
Hey @micahbales, I'm going to close this issue for now assuming you were successfully able to get Primrose running locally. If you have any other issues just reopen this issue and we will address them.
